"use client";

import { useState } from "react";
import OptionWheel from "@/components/ui/OptionWheel";
import { ScrollReveal } from "@/components/ui/scroll-reveal";

const USE_CASES = [
  {
    label: "Newsrooms",
    title: "Protect journalistic integrity",
    description: "Verify breaking news footage, user-generated content, and leaked audio before publication. Prevent retractions and maintain your audience's trust in an era of synthetic media."
  },
  {
    label: "Social Media",
    title: "Stop viral misinformation",
    description: "Automatically scan uploads at scale to flag deepfakes, synthetic audio, and recycled context before they reach millions of users and impact elections or markets."
  },
  {
    label: "E-Commerce",
    title: "Prevent identity and review fraud",
    description: "Ensure product reviews, seller verification videos, and customer support interactions aren't generated by AI bots or deepfake avatars."
  },
  {
    label: "Governments",
    title: "Secure public communications",
    description: "Monitor state-sponsored disinformation campaigns, verify diplomatic communications, and protect elections from synthetic manipulation."
  },
  {
    label: "Insurance",
    title: "Detect fraudulent claims",
    description: "Analyze submitted photos and videos for invisible tampering, metadata stripping, or generative artifacts to stop false claims in their tracks."
  },
  {
    label: "Cybersecurity",
    title: "Defend against social engineering",
    description: "Equip your SOC with tools to detect voice-cloned CEO fraud, synthetic phishing videos, and deepfake-powered social engineering attacks."
  }
];

export function UseCases() {
  const [activeIndex, setActiveIndex] = useState(2); // Default to E-Commerce for demo
  const activeCase = USE_CASES[activeIndex];

  return (
    <section className="border-b border-slate-200 dark:border-slate-800 bg-slate-900 overflow-hidden relative text-white">
      <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24 relative z-10">
        <ScrollReveal variant="fade-up" className="max-w-2xl mb-12">
          <p className="font-mono text-xs uppercase tracking-wide text-indigo-400">
            Built for Enterprise
          </p>
          <h2 className="mt-2 font-display text-2xl font-semibold tracking-tight text-white sm:text-3xl">
            Trusted by organizations that can't afford to be wrong
          </h2>
        </ScrollReveal>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center min-h-[400px]">
          {/* Wheel Container */}
          <ScrollReveal variant="fade-right" delay={0.2} className="relative h-[400px] w-full rounded-2xl bg-slate-800/50 border border-slate-700/50 shadow-inner overflow-hidden flex items-center">
            {/* Gradient mask for fading out edges */}
            <div className="absolute inset-0 pointer-events-none bg-gradient-to-b from-slate-900/80 via-transparent to-slate-900/80 z-10" />
            
            <div className="absolute inset-y-0 left-0 w-full">
              <OptionWheel
                items={USE_CASES.map(u => u.label)}
                defaultSelected={2}
                textColor="#64748b" // slate-500
                activeColor="#ffffff" // white
                side="left"
                fontSize={3}
                spacing={1.5}
                curve={1}
                tilt={8}
                blur={2}
                fade={0.3}
                inset={50}
                onChange={(index: number) => setActiveIndex(index)}
              />
            </div>
          </ScrollReveal>

          {/* Details Container */}
          <ScrollReveal variant="fade-left" delay={0.4} className="flex flex-col justify-center">
            <div className="bg-slate-800/30 border border-slate-700/50 p-8 rounded-2xl backdrop-blur-md">
              <span className="text-xs font-mono text-indigo-400 tracking-wider uppercase mb-3 block">
                {activeCase.label}
              </span>
              <h3 className="text-2xl font-display font-medium text-white mb-4">
                {activeCase.title}
              </h3>
              <p className="text-slate-400 leading-relaxed">
                {activeCase.description}
              </p>
            </div>
          </ScrollReveal>
        </div>
      </div>
    </section>
  );
}
